package com.olivier.commandcenter.remote

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.cert.CertificateException
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate

class CertPinTest {
    private fun resource(name: String): String =
        requireNotNull(javaClass.classLoader?.getResourceAsStream(name)) { "missing test resource $name" }
            .bufferedReader().readText()

    // test/fixtures/remote-proto/cert.pem: generated by the desktop's remotecert.js
    private fun fixtureCert(): X509Certificate =
        CertificateFactory.getInstance("X.509")
            .generateCertificate(resource("cert.pem").byteInputStream()) as X509Certificate

    private val fixture by lazy { JSONObject(resource("cert.json")) }

    @Test
    fun parseAcceptsNormalizedAndNodeStyleFingerprints() {
        val normalized = CertPin.parse(fixture.getString("fingerprint"))
        val nodeStyle = CertPin.parse(fixture.getString("fingerprint256"))
        assertEquals(32, normalized.size)
        assertArrayEquals(normalized, nodeStyle)
    }

    @Test
    fun parseRejectsWrongLengthAndNonHex() {
        assertThrows(IllegalArgumentException::class.java) { CertPin.parse("a1b2") }
        assertThrows(IllegalArgumentException::class.java) { CertPin.parse("z".repeat(64)) }
        assertThrows(IllegalArgumentException::class.java) { CertPin.parse("") }
    }

    @Test
    fun desktopGeneratedCertMatchesTheDesktopPin() {
        // The cross-implementation contract: Kotlin's SHA-256 of the leaf DER
        // equals the pin Node put in the pairing QR.
        val pin = CertPin.parse(fixture.getString("fingerprint"))
        assertTrue(CertPin.matches(fixtureCert(), pin))
    }

    @Test
    fun aDifferentPinDoesNotMatch() {
        val pin = CertPin.parse("00".repeat(32))
        assertFalse(CertPin.matches(fixtureCert(), pin))
    }

    @Test
    fun trustManagerAcceptsOnlyThePinnedLeaf() {
        val cert = fixtureCert()
        val good = PinTrustManager(CertPin.parse(fixture.getString("fingerprint")))
        good.checkServerTrusted(arrayOf(cert), "ECDHE_ECDSA") // no throw

        val bad = PinTrustManager(CertPin.parse("00".repeat(32)))
        assertThrows(CertificateException::class.java) { bad.checkServerTrusted(arrayOf(cert), "ECDHE_ECDSA") }
        assertThrows(CertificateException::class.java) { good.checkServerTrusted(arrayOf(), "ECDHE_ECDSA") }
        assertThrows(CertificateException::class.java) { good.checkClientTrusted(arrayOf(cert), "ECDHE_ECDSA") }
        assertEquals(0, good.acceptedIssuers.size)
    }
}
